name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump event context
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: echo "$EVENT_CONTEXT"

      # Trigger Azure DevOps pipeline to publish the extension
      - uses: tjcorr/pipelines@v1.4
        with:
          azure-devops-project-url: "${{ secrets.AZURE_DEVOPS_PROJECT_URL }}"
          azure-pipeline-id: 94
          azure-devops-token: "${{ secrets.AZURE_DEVOPS_TOKEN }}"
          #azure-pipeline-variables: '{"environment": "production"}'
          # azure-template-parameters: '{"param1": "value1", "param2": "value2"}'
          # source-branch: "${{ github.ref }}"
          source-version: "${{ github.sha }}"
