name: "version"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      NBGV_SemVer2: ${{ steps.gitversion.outputs.NBGV_SemVer2 }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history for GitVersioning

      - run: |
          npm ci
          npx nbgv cloud --all-vars
        working-directory: extension

      - name: gitversion
        id: gitversion
        run: |
          echo "NBGV_SemVer2=$NBGV_SemVer2" >> $GITHUB_OUTPUT
          

  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    needs: [version]
    env:
      NBGV_SemVer2: ${{ needs.version.outputs.NBGV_SemVer2 }}

    if: github.ref == 'refs/heads/main' # Running this job only for master branch
    steps:
      - uses: actions/checkout@v4

      - uses: release-drafter/release-drafter@v6
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ needs.version.outputs.NBGV_SemVer2 }}
